#!/usr/bin/env node
/**
 * Single source of truth for README / category / tag page generation.
 *
 * Previously this logic was duplicated: an orphaned scripts/generate-readmes.js
 * (never invoked) and an inlined copy inside .github/workflows/05-generate-readmes.yml.
 * They drifted. This .cjs file is now the only generator; the workflow invokes it.
 *
 * Run: node scripts/generate-readmes.cjs   (reads ./repos.yml, writes ./README.md,
 *      ./categories/*.md, ./tags/*.md)
 */
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// 1. Load data
if (!fs.existsSync('repos.yml')) {
  console.log('No repos.yml found');
  process.exit(1);
}
let data;
try {
  data = yaml.load(fs.readFileSync('repos.yml', 'utf8'));
} catch (e) {
  console.error('Failed to load repos.yml:', e.message);
  process.exit(1);
}
const repos = data.repositories || [];

// 2. Prepare directories
['categories', 'tags'].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// 3. Helpers
const windowsReservedNames = new Set([
  'CON', 'PRN', 'AUX', 'NUL',
  'COM1', 'COM2', 'COM3', 'COM4', 'COM5', 'COM6', 'COM7', 'COM8', 'COM9',
  'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', 'LPT6', 'LPT7', 'LPT8', 'LPT9',
]);

// Filesystem-safe filename: handles ':' namespaces, invalid chars, and Windows
// reserved names. Used for BOTH the written file and the link, so they always match.
const sanitizeFilename = (text) => {
  if (!text || typeof text !== 'string') return 'unnamed';
  let safe = text.replace(/:/g, '-').replace(/[<>"|?*/\\]/g, '-');
  safe = safe.replace(/-+/g, '-').replace(/^-+|-+$/g, '');
  const lastDot = safe.lastIndexOf('.');
  const base = lastDot > 0 ? safe.substring(0, lastDot) : safe;
  if (windowsReservedNames.has(base.toUpperCase())) safe = '_' + safe;
  return safe || 'unnamed';
};

// Escape Markdown control chars; `|` is included so descriptions can't break table columns.
const escapeMd = (text) => (text || '').replace(/([*_`\[\]|])/g, '\\$1');

// Guard invalid dates so one bad timestamp can't throw and abort the whole run.
const formatDate = (iso) => {
  if (!iso) return 'N/A';
  const d = new Date(iso);
  return isNaN(d.getTime()) ? 'N/A' : d.toISOString().split('T')[0];
};

const renderRepoRow = (repo) => {
  const stars = repo.github_metadata?.stargazers_count || 0;
  const lang = repo.github_metadata?.language || '';
  const pushed = formatDate(repo.github_metadata?.repo_pushed_at);
  const desc = (repo.summary || 'No description').replace(/\n/g, ' ');
  const name = repo.repo;
  const url = repo.github_metadata?.html_url || `https://github.com/${name}`;

  const badges = [];
  if (lang) badges.push(`\`${lang}\``);
  if (stars > 1000) badges.push(`★ ${Math.round(stars / 100) / 10}k`);
  else if (stars > 0) badges.push(`★ ${stars}`);

  return `| [${name}](${url}) | ${escapeMd(desc)} | ${badges.join(' ')} | ${pushed} |`;
};

const renderTableHeader = () => `| Repository | Description | Metadata | Last Pushed |\n|---|---|---|---|`;

// 4. Category pages
const categories = {};
repos.forEach(r => {
  (r.categories || []).forEach(c => {
    if (!categories[c]) categories[c] = [];
    categories[c].push(r);
  });
});

const generatedCategories = new Set();
Object.entries(categories).forEach(([cat, items]) => {
  const sorted = items.sort((a, b) => new Date(b.user_starred_at) - new Date(a.user_starred_at));
  const content = `# ${cat.charAt(0).toUpperCase() + cat.slice(1)}\n\n` +
    `*${sorted.length} repositories*\n\n` +
    `[← Back to Index](../README.md)\n\n` +
    renderTableHeader() + '\n' +
    sorted.map(renderRepoRow).join('\n') + '\n\n' +
    `*Generated by [GitHub Stars Curation](https://github.com/4444J99/github-stars)*`;
  const filename = sanitizeFilename(cat) + '.md';
  fs.writeFileSync(`categories/${filename}`, content);
  generatedCategories.add(filename);
});

// 5. Tag pages (skip language tags and sparse tags)
const tags = {};
repos.forEach(r => {
  (r.tags || []).forEach(t => {
    if (t.startsWith('lang:')) return;
    if (!tags[t]) tags[t] = [];
    tags[t].push(r);
  });
});

const generatedTags = new Set();
Object.entries(tags).forEach(([tag, items]) => {
  if (items.length < 2) return;
  const sorted = items.sort((a, b) => new Date(b.user_starred_at) - new Date(a.user_starred_at));
  const content = `# Tag: ${tag}\n\n` +
    `*${sorted.length} repositories*\n\n` +
    `[← Back to Index](../README.md)\n\n` +
    renderTableHeader() + '\n' +
    sorted.map(renderRepoRow).join('\n');
  const filename = sanitizeFilename(tag) + '.md';
  fs.writeFileSync(`tags/${filename}`, content);
  generatedTags.add(filename);
});

// Cleanup orphaned files
const cleanupOrphans = (dir, validFiles) => {
  if (!fs.existsSync(dir)) return;
  const orphans = fs.readdirSync(dir).filter(f => f.endsWith('.md') && !validFiles.has(f));
  orphans.forEach(f => {
    fs.unlinkSync(path.join(dir, f));
    console.log(`Removed orphaned file: ${dir}/${f}`);
  });
};
cleanupOrphans('categories', generatedCategories);
cleanupOrphans('tags', generatedTags);

// 6. Main index
const stats = {
  total: repos.length,
  categories: Object.keys(categories).length,
  tags: Object.keys(tags).length,
};

// Only link tags that actually have a generated page (>= 2 repos).
const topTags = Object.entries(tags)
  .filter(([, i]) => i.length >= 2)
  .sort((a, b) => b[1].length - a[1].length)
  .slice(0, 30)
  .map(([t, i]) => `[${t}](tags/${sanitizeFilename(t)}.md) (${i.length})`);

let indexContent = `# Awesome Starred Repositories\n\n` +
  `> A curated list of **${stats.total}** repositories across **${stats.categories}** categories, automatically classified and organized.\n\n` +
  `Last updated: ${new Date().toISOString().split('T')[0]}\n\n`;

const recent = repos
  .slice()
  .sort((a, b) => new Date(b.user_starred_at) - new Date(a.user_starred_at))
  .slice(0, 10);

indexContent += `## ⭐ Recently Starred\n\n` +
  renderTableHeader() + '\n' +
  recent.map(renderRepoRow).join('\n') + '\n\n';

indexContent += `## 🏷️ Popular Tags\n\n` + topTags.join(' • ') + `\n\n`;

const catsByCount = Object.entries(categories)
  .sort((a, b) => b[1].length - a[1].length)
  .map(([cat, items]) => `[${cat}](categories/${sanitizeFilename(cat)}.md) (${items.length})`);

const cols = 3;
let catTable = '| | | |\n|---|---|---|\n';
for (let i = 0; i < catsByCount.length; i += cols) {
  const row = [];
  for (let j = 0; j < cols; j++) row.push(catsByCount[i + j] || '');
  catTable += `| ${row.join(' | ')} |\n`;
}

indexContent += `<details>\n<summary>📂 All Categories (${stats.categories})</summary>\n\n${catTable}\n</details>\n`;
indexContent += `\n---\n*Powered by [GitHub Stars Curation System](https://github.com/4444J99/github-stars)*`;

fs.writeFileSync('README.md', indexContent);
console.log(`README generation complete: ${stats.total} repos, ${generatedCategories.size} categories, ${generatedTags.size} tags.`);
